services:
  db:
    image: "postgres:latest"
    ports:
      - "5434:5432"
    environment:
      - "POSTGRES_USER=leap-sls"
      - "POSTGRES_PASSWORD=postgres"
  db-test:
    image: "postgres:latest"
    ports:
      - "5435:5432"
    environment:
      - "POSTGRES_USER=leap-sls-test"
      - "POSTGRES_PASSWORD=postgres"