# fly.toml app configuration file generated for leap-sls on 2024-09-30T17:16:27+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'leap-sls'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[deploy]
  release_command = "npm run db:prod:migrate"
